version: 1

applications:
  - appRoot: id-music-front
    frontend:
      phases:
        preBuild:
          commands:
            - echo "Installing dependencies"
            - yarn install
        build:
          commands:
            - echo "Building the app"
            - yarn run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
